name: pytorch-template
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9.19
  - pip==23.3.1
  - pytorch=2.2.2
  - torchvision=0.17.2
  - lightning[pytorch-extra]==2.2.1
  - numpy=1.26.4
  - pandas==2.2.1
  - matplotlib==3.8.0
  - pip:
      - black==24.3.0
      - isort==5.13.2
      - fastapi==0.110.1
      - uvicorn==0.29.0
      - gradio==4.25.0
      - tensorboard==2.16.2
      - tqdm==4.66.2